SELECT * FROM T_TODAY_DATA;
SELECT * FROM T_REAL_DATA;
SELECT * FROM T_LIVE_DATA;
SELECT * FROM T_SEVEN_DATA;
SELECT * FROM T_LIVE_DATA2;

DELETE T_TODAY_DATA;
DELETE T_REAL_DATA;
DELETE T_LIVE_DATA;
DELETE T_SEVEN_DATA;
DELETE T_LIVE_DATA2;

